// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Chess_API.Infrastructure.Data;

#nullable disable

namespace Online_Chess_API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20250524102802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Online_Chess_API.Core.Models.ChessGame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_id");

                    b.Property<string>("BlackId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("black_id");

                    b.Property<int>("BlackRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("black_rating");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasMaxLength(1413)
                        .HasColumnType("TEXT")
                        .HasColumnName("moves");

                    b.Property<string>("OpeningCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_code");

                    b.Property<string>("OpeningFullname")
                        .IsRequired()
                        .HasMaxLength(91)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_fullname");

                    b.Property<int>("OpeningMoves")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_moves");

                    b.Property<string>("OpeningResponse")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_response");

                    b.Property<string>("OpeningShortname")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_shortname");

                    b.Property<string>("OpeningVariation")
                        .HasMaxLength(47)
                        .HasColumnType("TEXT")
                        .HasColumnName("opening_variation");

                    b.Property<string>("Rated")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("rated");

                    b.Property<string>("TimeIncrement")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_increment");

                    b.Property<int>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.Property<string>("VictoryStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("victory_status");

                    b.Property<string>("WhiteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("white_id");

                    b.Property<int>("WhiteRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("white_rating");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("winner");

                    b.HasKey("GameId");

                    b.ToTable("ChessGames", (string)null);
                });

            modelBuilder.Entity("Online_Chess_API.Core.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Online_Chess_API.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Online_Chess_API.Core.Models.Comment", b =>
                {
                    b.HasOne("Online_Chess_API.Core.Models.ChessGame", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Chess_API.Core.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Chess_API.Core.Models.ChessGame", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Online_Chess_API.Core.Models.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
